name: Streamlit CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Langkah untuk setup Docker Buildx, login ke DockerHub, dll
      # Jika Anda membangun dan push image Docker ke DockerHub

      - name: Build Docker Image
        run: |
          docker build -t my-streamlit-app .
      
      - name: Run Docker Container
        run: |
          docker run -d -p 5005:5000 --name streamlit-app my-streamlit-app

      - name: Wait for Streamlit to be ready
        run: |
          echo "Waiting for Streamlit app to be ready..."
          sleep 10  # Tunggu 10 detik sebelum melakukan curl pertama
          count=0
          until curl -s http://localhost:5005 > /dev/null || [ $count -eq 5 ]; do
            echo "Still waiting for Streamlit app to be ready..."
            sleep 10
            ((count++))
          done
          if [ $count -eq 5 ]; then
            echo "Timeout: Streamlit app took too long to start."
            exit 1
          fi
          echo "Streamlit app is up and running!"

      - name: Run tests
        run: |
          curl http://localhost:5005  # Gantikan dengan uji tes yang sesuai untuk aplikasi Streamlit Anda

      - name: Tear down
        run: |
          docker stop streamlit-app
          docker rm streamlit-app
