test:
  runs-on: ubuntu-latest
  needs: build

  services:
    docker:
      image: docker:19.03.12
      options: --privileged

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Pull Docker Image
      run: docker pull talithaarr/mlops-ps0:v1

    - name: Run Docker Container
      run: |
        docker run -d --name my-app-container \
          -p 5003:5000 \
          talithaarr/mlops-ps0:v1

    - name: Verify Application Accessibility
      run: |
        sleep 10 # Give time for the application to start
        curl -f http://localhost:5003 || exit 1

    - name: Cleanup
      run: docker rm -f my-app-container
