name: Streamlit CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest
    
      - name: Ensure Vendor and Storage Directories Exist
        run: |
          mkdir -p vendor storage/logs
          sudo chown -R $USER:$USER vendor storage
    
      - name: Install Composer Dependencies
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/www \
            -w /var/www \
            ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest \
            composer install --no-interaction --prefer-dist
    
      - name: Install Python Dependencies
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/www \
            -w /var/www \
            ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest \
            pip install -r requirements.txt
    
      - name: Run Docker Container and Execute Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/www \
            -w /var/www \
            --user root \
            -p 5003:5000 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest \
            python app.py

      - name: Start Application for Accessibility Check
        run: |
          docker run -d --name my-app-container \
            -v ${{ github.workspace }}:/var/www \
            -w /var/www \
            -p 5003:5000 \
            --user root \
            ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest \
            python app.py

      - name: Verify Application Accessibility
        run: |
          sleep 10 # Give time for the application to start
          curl -f http://localhost:5003 || exit 1

      - name: Cleanup
        run: docker rm -f my-app-container
