name: Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Ganti 'x' dengan versi Python yang Anda gunakan

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit

      - name: Run Docker container
        run: docker run -p 5003:5000 my-streamlit-app2
